budgetlens/budgetlens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

budgetlens/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('upload/', views.upload_receipt, name='upload'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
    path('expense/<int:expense_id>/', views.expense, name='expense'),
    path('save_expense/<int:expense_id>/', views.save_expense, name='save_expense'),
]

budgetlens/core/models.py
"""This module contains the models for the core app."""
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Expense(models.Model):
    """Model to store the expense details"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    receipt_image = models.ImageField(upload_to="receipts/")
    expense_date = models.DateField(blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    currency = models.CharField(max_length=3, blank=True, null=True)
    amount_in_target_currency = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    BASE_CATEGORIES = [
        "Housing", "Utilities", "Transportation", "Groceries", "Dining Out", "Healthcare",
        "Debt Payments", "Insurance", "Clothing", "Entertainment", "Education", "Childcare",
        "Pet Care", "Subscriptions", "Miscellaneous"
    ]

    # Create choices for the category field
    CATEGORY_CHOICES = [(category, category) for category in BASE_CATEGORIES]

    # Update the category field to use choices
    category = models.CharField(
        max_length=100,
        choices=CATEGORY_CHOICES,
        blank=True,
        null=True
    )

    def __str__(self):
        return f"{self.category} - {self.amount} {self.currency} on {self.expense_date}"

class UserProfile(models.Model):
    """Model to store the user's profile details"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    target_currency = models.CharField(max_length=3, blank=True, null=True, default="EUR")
    objects = models.Manager()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Signal to create a user profile when a new user is created"""
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """Signal to save the user profile when the user is updated"""
    instance.userprofile.save()

budgetlens/core/forms.py
from django import forms
from .models import Expense

class ExpenseForm(forms.ModelForm):
    """Form to upload an expense"""
    class Meta:
        model = Expense
        fields = ['receipt_image', 'category', 'expense_date', 'amount', 'currency']
        widgets = {
            'category': forms.TextInput(attrs={'required': False}),
            'expense_date': forms.DateInput(attrs={'required': False}),
            'amount': forms.NumberInput(attrs={'required': False}),
            'currency': forms.TextInput(attrs={'required': False}),
        }

class ExpenseEditForm(forms.ModelForm):
    """Form to edit an expense"""
    class Meta:
        model = Expense
        fields = ['category', 'expense_date', 'amount', 'currency']
        widgets = {
            'category': forms.Select(choices=Expense.CATEGORY_CHOICES),
        }
        

budgetlens/core/views.py
"""Views for the core app"""

import base64
from decimal import Decimal
import logging
import json
import os
import requests
from django.db.models import Sum, F, Value, FloatField
from django.db.models.functions import Lower, Trim, Coalesce
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from openai import OpenAI
from .forms import ExpenseEditForm, ExpenseForm
from .models import Expense, UserProfile


OPEN_EXCHANGE_RATES_API_KEY = os.getenv("OPEN_EXCHANGE_RATES_API_KEY")
OPEN_EXCHANGE_RATES_API_URL = "https://openexchangerates.org/api/historical/"

log = logging.getLogger(__name__)
client = OpenAI()


def encode_image(image_path):
    """Encode the image file to base64 string"""
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")


def process_receipt(image_path):
    """Process the receipt image using OpenAI API"""
    log.debug("views : process_receipt()")
    base64_image = encode_image(image_path)
    category = "Sample Category"
    expense_date = "2024-11-13"
    amount = 10.00
    currency = "EUR"

    base_categories = [
        "Housing",
        "Utilities",
        "Transportation",
        "Groceries",
        "Dining Out",
        "Healthcare",
        "Debt Payments",
        "Insurance",
        "Clothing",
        "Entertainment",
        "Education",
        "Childcare",
        "Pet Care",
        "Subscriptions",
        "Miscellaneous",
    ]

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": (
                            "Analyze the provided receipt and extract the following details: "
                            "1. Category: Determine the category of the expense from this list: "
                            f"{', '.join(base_categories)}. 2.Date: Identify the transaction date. "
                            "3. Amount: Extract the expense amount as a decimal number. Consider: "
                            "- A comma may serve as a thousand separator or decimal separator. "
                            "- In KRW (Korean Won), the amount is never lower than a thousand. "
                            "4. Currency: Identify the currency used in the expense starting "
                            "(three-character ISO 4217 code). Respond strictly in JSON format, "
                            "and ending with braces, without any additional markup language "
                            'or explanation. Example response: {"category": "<category>",'
                            ' "date": "<date>", "amount": <amount>,'
                            ' "currency": "<currency>"}'
                        ),
                    },
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"},
                    },
                ],
            }
        ],
        temperature=0.2,
    )

    try:
        if (
            not response
            or not response.choices
            or not response.choices[0].message.content
        ):
            raise ValueError("Empty or invalid response from OpenAI API")

        content = response.choices[0].message.content.strip()
        log.debug("Response from OpenAI")
        log.debug(content)

        if content.startswith("```json") and content.endswith("```"):
            log.debug("Content: %s", content)
            content = content[7:-3].strip()
            log.debug("Content after stripping markdown: %s", content)

        response_data = json.loads(content)

        if "/" in response_data.get("date"):
            response_data["date"] = response_data["date"].replace("/", "-")

        category = response_data.get("category", "Miscellaneous")
        if category not in base_categories:
            category = "Miscellaneous"

        expense_date = response_data.get("date")
        amount = response_data.get("amount")
        currency = response_data.get("currency").upper()

        return category, expense_date, amount, currency
    except json.JSONDecodeError as e:
        log.error("JSON decode error: %s", e)
        raise
    except ValueError as e:
        log.error("Value error: %s", e)
        raise
    except Exception as e:
        log.error("Unexpected error: %s", e)
        raise


def get_exchange_rate(date, from_currency, to_currency):
    """Get the exchange rate for the given date and currencies"""

    if from_currency == to_currency:
        return 1, 1

    log.debug("views : get_exchange_rate()")
    url = f"{OPEN_EXCHANGE_RATES_API_URL}{date}.json"
    log.debug("URL: %s", url)
    params = {"app_id": OPEN_EXCHANGE_RATES_API_KEY}
    response = requests.get(url, params=params, timeout=10)

    if response.status_code == 200:
        data = response.json()
        return data["rates"].get(from_currency), data["rates"].get(to_currency)

    log.error("Error fetching exchange rate: %s", response.text)
    return None, None


@login_required
def upload_receipt(request):
    """View to upload the receipt image and process it"""
    log.debug("views : upload_receipt()")
    if request.method == "POST":
        form = ExpenseForm(request.POST, request.FILES)
        if form.is_valid():
            expense_dto = form.save(commit=False)
            expense_dto.user = request.user
            expense_dto.save()

            category, expense_date, amount, currency = process_receipt(
                expense_dto.receipt_image.path
            )

            expense_dto.category = category
            expense_dto.expense_date = expense_date
            expense_dto.amount = amount
            expense_dto.currency = currency

            user_profile = UserProfile.objects.get(user=request.user)
            target_currency = user_profile.target_currency

            exchange_rate_to_usd, exchange_rate_to_target = get_exchange_rate(
                expense_date, currency, target_currency
            )
            log.debug(
                "Exchange rates: to USD %s, to target %s",
                exchange_rate_to_usd,
                exchange_rate_to_target,
            )

            if exchange_rate_to_usd and exchange_rate_to_target:
                exchange_rate_to_usd = Decimal(str(exchange_rate_to_usd))
                exchange_rate_to_target = Decimal(str(exchange_rate_to_target))
                amount_decimal = Decimal(str(amount))

                converted_amount_to_usd = amount_decimal / exchange_rate_to_usd
                converted_amount_to_target = (
                    converted_amount_to_usd * exchange_rate_to_target
                )
                expense_dto.amount_in_target_currency = round(
                    converted_amount_to_target, 2
                )
                log.debug("Converted amount: %s", expense_dto.amount_in_target_currency)
            else:
                log.error("Could not convert amount to target currency")

            expense_dto.save()
            # Redirect to the expense page to adjust information
            return redirect("expense", expense_id=expense_dto.id)
        else:
            log.error("Form errors: %s", form.errors)
    else:
        form = ExpenseForm()
    return render(request, "upload.html", {"form": form})


@login_required
def dashboard(request):
    """View to display the user's expenses ordered by date and aggregated by category"""
    expenses = Expense.objects.filter(user=request.user).order_by("-expense_date")

    expenses = expenses.annotate(category_normalized=Trim(Lower(F("category"))))
    log.debug("Normalized Category: %s", expenses.values("category_normalized"))

    category_data = (
        expenses.values("category_normalized")
        .annotate(
            total_amount=Coalesce(
                Sum("amount_in_target_currency", output_field=FloatField()),
                Value(0, output_field=FloatField()),
            )
        )
        .order_by("category_normalized")
    )

    categories = [
        (
            item["category_normalized"].capitalize()
            if item["category_normalized"]
            else "Uncategorized"
        )
        for item in category_data
    ]
    amounts = [float(item["total_amount"]) for item in category_data]

    log.debug("Aggregated Category Data: %s", categories)

    return render(
        request,
        "dashboard.html",
        {
            "expenses": expenses,
            "categories": json.dumps(categories),
            "amounts": json.dumps(amounts),
        },
    )


@login_required
def expense(request, expense_id):
    """View to display the details of a specific expense"""
    log.debug("views : expense()")
    log.debug("Expense ID: %s", expense_id)
    expense_detail = Expense.objects.get(id=expense_id, user=request.user)
    log.debug("Expense detail: %s", expense_detail.expense_date)
    log.debug("User Currency: %s", request.user.userprofile.target_currency)
    return render(
        request, "expense.html", {"expense": expense_detail, "user": request.user}
    )


@login_required
def save_expense(request, expense_id):
    """View to save the edited expense details with currency conversion"""
    log.debug("views : save_expense()")
    expense_edit = Expense.objects.get(id=expense_id, user=request.user)

    if request.method == "POST":
        form = ExpenseEditForm(request.POST, instance=expense_edit)
        if form.is_valid():
            expense_form = form.save(commit=False)

            user_profile = UserProfile.objects.get(user=request.user)
            target_currency = user_profile.target_currency

            exchange_rate_to_usd, exchange_rate_to_target = get_exchange_rate(
                expense_form.expense_date, expense_form.currency, target_currency

budgetlens/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Budget Lens{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/mvp.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body style="text-align: center;">
    <header style="padding: 0rem 1rem;">
        <h1>Budget Lens</h1>
        {% if user.is_authenticated %}
        <nav style="justify-content: center; margin-bottom: 0rem; margin-right: 1rem;">
            <ul style="display: flex; list-style: none; padding: 0;">
                <li>
                    <form action="{% url 'dashboard' %}" method="post" style="display: inline; border: none; box-shadow: none;">
                        {% csrf_token %}
                        <button type="submit" style="font-size: 0.8em; padding: 5px 10px;">Dashboard</button>
                    </form>
                </li>
                <li>
                    <form action="{% url 'upload' %}" method="post" style="display: inline; border: none; box-shadow: none;">
                        {% csrf_token %}
                        <button type="submit" style="font-size: 0.8em; padding: 5px 10px;">Upload</button>
                    </form>
                </li>
                <li>
                    <form action="{% url 'logout' %}" method="post" style="display: inline; border: none; box-shadow: none;">
                        {% csrf_token %}
                        <button type="submit" style="font-size: 0.8em; padding: 5px 10px;">Log Out</button>
                    </form>
                </li>
            </ul>
        </nav>
        {% endif %}
    </header>
    <main style="padding: 1rem;">
        {% block content %}
        <!-- Content goes here -->
        {% endblock %}
    </main>
    <footer style="text-align: center;">
        <p>&copy; 2024 1oannis.com - All rights reserved.</p>
    </footer>
</body>
</html>

budgetlens/core/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<h2>Dashboard</h2>

{% if amounts|length > 0 %}
<div style="width: 100%; max-width: 600px; height: 400px; margin: auto;">
    <canvas id="expensesChart"></canvas>
</div>
{% else %}
    <p>No expenses to display.</p>
{% endif %}

<!-- Existing table -->
<div style="max-height: 400px; overflow-y: auto;">
    <table style="width: 100%; border-collapse: collapse;">
        <thead>
            <tr>
                <th>Category</th>
                <th>Amount</th>
                <th>Currency</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in expenses %}
            <tr onclick="window.location.href='{% url 'expense' expense.id %}'" style="cursor: pointer;">
                <td>{{ expense.category }}</td>
                <td>{{ expense.amount }}</td>
                <td>{{ expense.currency }}</td>
                <td>{{ expense.expense_date }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Script to render the chart -->
<script>
    var ctx = document.getElementById('expensesChart').getContext('2d');
    var expensesChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: {{ categories|safe }},
            datasets: [{
                data: {{ amounts|safe }},
                backgroundColor: [
                    '#FF6384',
                    '#36A2EB',
                    '#FFCE56',
                    '#4BC0C0',
                    '#9966FF',
                    '#FF9F40',
                ],
                hoverBackgroundColor: [
                    '#FF6384',
                    '#36A2EB',
                    '#FFCE56',
                    '#4BC0C0',
                    '#9966FF',
                    '#FF9F40',
                ]
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    position: 'bottom',
                },
                title: {
                    display: true,
                    text: 'Expenses by Category'
                }
            }
        }
    });
</script>
{% endblock %}

budgetlens/core/templates/expense.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Edit Expense</h2>
    <form action="{% url 'save_expense' expense.id %}" method="post">
        {% csrf_token %}
        {% if form.errors %}
            <div class="error">
                {{ form.errors }}
            </div>
        {% endif %}
        <div class="form-group">
            <label for="id_category">Category:</label>
            <input type="text" id="id_category" name="category" value="{{ expense.category }}" required>
        </div>

        <div class="form-group" style="display: flex; gap: 10px; align-items: center;">
            <div>
                <label for="id_amount">Amount:</label>
                <input type="number" id="id_amount" name="amount" value="{{ expense.amount }}" required>
            </div>
            <div>
                <label for="id_currency">Currency:</label>
                <input type="text" id="id_currency" name="currency" value="{{ expense.currency }}" required>
            </div>
        </div>

        <div class="form-group" style="display: flex; gap: 30px; align-items: center;">
            <div>
                <label for="targetAmount">Converted:</label>
                <p id="targetAmount">{{ expense.amount_in_target_currency }}</p>
            </div>
            <div>
                <label for="targetCurrency">Target Currency:</label>
                <p id="targetCurrency">{{ user.userprofile.target_currency }}</p>
            </div>
        </div>

        <div class="form-group">
            <label for="id_expense_date">Date:</label>
            <input type="date" id="id_expense_date" name="expense_date" value="{{ expense.expense_date|date:'Y-m-d' }}" required>
        </div>

        <div class="form-group">
            <button type="submit">Save</button>
        </div>
    </form>
</div>
{% endblock %}

budgetlens/core/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<p>Hi {{ user.username }}!</p>
<p><a href="{% url 'password_change' %}">Password Change</a></p>
{% else %}
<div style="text-align: center;">
    <p>You are not logged in</p>
    <p>
        <a href="{% url 'login' %}" style="margin-right: 10px;">Log In</a>
        <a href="{% url 'signup' %}" style="margin-right: 10px;">Sign Up</a>
        <a href="{% url 'password_reset' %}">Password Reset</a>
    </p>
</div>
{% endif %}
{% endblock %}

budgetlens/core/templates/upload.html
{% extends 'base.html' %}

{% block content %}
  <h2>Upload Receipt</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.receipt_image.label_tag }} {{ form.receipt_image }}
    <button type="submit">Upload</button>
  </form>

  {% if response %}
    <h3>Processed Receipt Details:</h3>
    <ul>
      <li><strong>Category:</strong> {{ response.category }}</li>
      <li><strong>Expense Date:</strong> {{ response.expense_date }}</li>
      <li><strong>Amount:</strong> {{ response.amount }}</li>
      <li><strong>Currency:</strong> {{ response.currency }}</li>
      <li><strong>Converted:</strong> {{ response.amount_in_target_currency }}</li>
    </ul>
  {% endif %}
{% endblock %}

<script>
    document.querySelector("form").onsubmit = async function(event) {
      event.preventDefault();
      let formData = new FormData(this);
      let response = await fetch("{% url 'upload' %}", {
        method: "POST",
        body: formData,
      });
      let result = await response.text();
      document.body.innerHTML = result;
    };
</script>
  